
version: '3'
services:
  app:
    image: elikloft/ipfs-service:latest
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=development
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=development
      - DATABASE_HOST=database.service.pinning.internal
      - REDIS_URL=redis://redis.service.pinning.internal
      - IPFS_URL=ipfs.service.pinning.internal
    networks:
      - internal
    depends_on:
      - database.service.pinning.internal
      - redis.service.pinning.internal
      - ipfs.service.pinning.internal

  database.service.pinning.internal:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=development

  redis.service.pinning.internal:
    image: redis:6.0-alpine
    networks:
      - internal

  ipfs.service.pinning.internal:
    image: ipfs/go-ipfs:latest
    networks:
      - internal
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
